### ISSUE TITLE
Video working ?

### ISSUE THREAD

**Issue by dj-nest** [gianlucarenzi/stalker#2]
Hello. 
I searched youtube and didnt find any video with info using this adapter 
Is there any more information or video of a working board  ? 

thanks in advance
Billy (DJ NEST)

**Comment by gianlucarenzi** [comment]
Sorry for (very) late reply. I showed those hardware in Amiga37 and Amiga38 in Germany and in various RetroGaming/RetroComputers Festivals in Italy. As soon as possible I will post some videos.

**Comment by arnljot** [comment]
Only video I could find
